github.com:
    users:
        cmdada:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: cmdada
